// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.CryptoSync.Tests;

public partial class TestSyncContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("881d6ee9-8f03-4cad-ab3d-fe591755ff14"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            UpdatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.PUBLIC,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("a96de51b-f3d3-47c2-916e-afa52ec6df12"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("14b1c595-cfeb-42e0-8ac5-215778f294d9"),
                GroupContext = "self-881d6ee98f034cadab3dfe591755ff14:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("31f719d0-bfeb-48c4-8351-47919b25b5c4"),
                ShareGroupId = System.Guid.Parse("a96de51b-f3d3-47c2-916e-afa52ec6df12"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("8+iZuIiaMECuezqL5r3MzHXtTvSI9GtupWPIuDiq/rt//sutiFFqddADQTL40za9IzvPoFL1prvkNOSv"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("881d6ee9-8f03-4cad-ab3d-fe591755ff14"),
                UpdatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("7e27a769-de1b-438c-a415-8b07c571442a"),
                ShareGroupId = System.Guid.Parse("14b1c595-cfeb-42e0-8ac5-215778f294d9"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("F+b05Uz4Iq5oQxIovBIlBrhAAXiLZIWkZ44pWT/wTSMEn6M5b+2ukgW9HgJzedkdD+Hn9d1VjHVUJVVx"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("G2FjQsLYlGmI3TYUuMch+Ei4sHwA/kSyyH+czdyQBpG9Mae/H82bmp5BJWPP3R/ojdxyu0XanLSFbtVFGwuwDg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("881d6ee9-8f03-4cad-ab3d-fe591755ff14"),
                UpdatedAt = new System.DateTime(639116691358214260L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("d2ec376e-62e3-44a0-a435-f74cc887eb30"),
            ClientGuid = "c5ffcdad-e57a-4baa-8145-38630834477a",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("881d6ee9-8f03-4cad-ab3d-fe591755ff14"),
            OwnContactId = System.Guid.Parse("881d6ee9-8f03-4cad-ab3d-fe591755ff14")
        });

        modelBuilder.Entity<PermissionTableSignature>().HasData(new
        {
            Id = System.Guid.Parse("ece64655-8999-3ed3-a68d-25b617087d86"),
            PermissionHash = System.Convert.FromBase64String("RHfNKvUcl1cb6zx5OElLz/Of0zND7llnl3+2f34D9kQ="),
            AdminSignature = System.Convert.FromBase64String("sdtkn3Idw7b/FsV7Ir9BNYztq391A/KliDUFzR5lPjPSxF1/FtK2afxztlqDpEshC5cFtv9nH6Squ1awQFdiDw=="),
            AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA="
        });
    }
}