// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqliteWasmBlazor.Models;

#nullable disable

namespace SqliteWasmBlazor.Models.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.FTSTodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FTSTodoItem");

                    b.Property<double?>("Rank")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FTSTodoItem", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckpointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TombstoneCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncState");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoListId")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("todos");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("todoLists");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.TypeTestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("BlobValue")
                        .HasColumnType("BLOB");

                    b.Property<bool>("BoolValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ByteValue")
                        .HasColumnType("INTEGER");

                    b.Property<char>("CharValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateTimeOffsetValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<double>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int>("EnumValue")
                        .HasColumnType("INTEGER");

                    b.Property<float>("FloatValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GuidValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LongValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NullableBoolValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("NullableByteValue")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("NullableCharValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NullableDateTimeOffsetValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NullableDateTimeValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NullableDecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NullableDoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("NullableEnumValue")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("NullableFloatValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("NullableGuidValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NullableIntValue")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NullableLongValue")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("NullableShortValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NullableStringValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("NullableTimeSpanValue")
                        .HasColumnType("TEXT");

                    b.Property<short>("ShortValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpanValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypeTests");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.FTSTodoItem", b =>
                {
                    b.HasOne("SqliteWasmBlazor.Models.Models.TodoItem", "TodoItem")
                        .WithOne("FTS")
                        .HasForeignKey("SqliteWasmBlazor.Models.Models.FTSTodoItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.Todo", b =>
                {
                    b.HasOne("SqliteWasmBlazor.Models.Models.TodoList", "TodoList")
                        .WithMany("Todos")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.TodoItem", b =>
                {
                    b.Navigation("FTS");
                });

            modelBuilder.Entity("SqliteWasmBlazor.Models.Models.TodoList", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
