using SqliteWasmBlazor.Crypto.Abstractions;
using SqliteWasmBlazor.Crypto.Abstractions.Services;
using SqliteWasmBlazor.Crypto.BouncyCastle;
using Microsoft.Extensions.DependencyInjection;
using SqliteWasmBlazor.CryptoSync;

// ============================================================================
// Admin Seed Generator
//
// Runs CryptoSyncBootstrap with a hardcoded test keypair and emits a .cs file
// with HasData calls that the consumer's DbContext includes in OnModelCreating.
//
// Usage: dotnet run -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output ../SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// ============================================================================

var contextName = "TestSyncContext";
var ns = "SqliteWasmBlazor.CryptoSync.Tests";
var outputPath = "../SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs";

for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--context" when i + 1 < args.Length:
            contextName = args[++i];
            break;
        case "--namespace" when i + 1 < args.Length:
            ns = args[++i];
            break;
        case "--output" when i + 1 < args.Length:
            outputPath = args[++i];
            break;
    }
}

// DI setup — ICryptoProvider resolved through container, not hardcoded.
var services = new ServiceCollection();
services.AddSingleton<ICryptoProvider, BouncyCastleCryptoProvider>();
services.AddSingleton<IGroupEncryption, GroupEncryptionService>();
services.AddSingleton<DeclarationSigner>();
services.AddSingleton<CryptoSyncBootstrap>();
var provider = services.BuildServiceProvider();

var crypto = provider.GetRequiredService<ICryptoProvider>();
var bootstrap = provider.GetRequiredService<CryptoSyncBootstrap>();

// Hardcoded test seed — deterministic so the generated file is stable across runs.
var adminSeed = new byte[32];
for (var i = 0; i < 32; i++)
{
    adminSeed[i] = (byte)(i + 1);
}
var adminKeys = await crypto.DeriveDualKeyPairAsync(adminSeed);

var seed = await bootstrap.CreateAdminSeedAsync(
    adminKeys,
    adminUsername: "TestAdmin",
    adminEmail: "admin@test.local",
    deviceName: "Seed Device");

var wrappedCekBase64 = Convert.ToBase64String(seed.AdminShareTarget.WrappedContentKey);
var selfWrappedCekBase64 = Convert.ToBase64String(seed.AdminSelfTarget.WrappedContentKey);
var adminSigBase64 = Convert.ToBase64String(seed.AdminShareTarget.AdminSignature);
var selfSigBase64 = Convert.ToBase64String(seed.AdminSelfTarget.AdminSignature);

// Permission table hash + signature.
// Resolve domain permissions from the target context's generated static method.
var allPermissions = ResolveAllPermissions(ns, contextName);
var permissionHash = PermissionTableHash.Compute(allPermissions);
var permHashBase64 = Convert.ToBase64String(permissionHash);

var adminEd25519Priv = Convert.FromBase64String(adminKeys.Ed25519PrivateKey);
byte[] permSignatureBytes;
try
{
    var permSignResult = await crypto.SignAsync(permHashBase64, adminEd25519Priv);
    if (!permSignResult.Success || permSignResult.Value is null)
    {
        throw new InvalidOperationException($"Failed to sign permission table: {permSignResult.ErrorCode}");
    }
    permSignatureBytes = Convert.FromBase64String(permSignResult.Value);
}
finally
{
    System.Security.Cryptography.CryptographicOperations.ZeroMemory(adminEd25519Priv);
}
var permSigBase64 = Convert.ToBase64String(permSignatureBytes);
var permSigGuid = CryptoSyncContextBase.DeterministicGuid("PermissionTableSignature:v1");

var code = $$"""
// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context {{contextName}} --namespace {{ns}} --output {{outputPath}}
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace {{ns}};

public partial class {{contextName}}
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "{{adminKeys.X25519PrivateKey}}";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "{{adminKeys.Ed25519PrivateKey}}";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "{{adminKeys.X25519PublicKey}}";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "{{adminKeys.Ed25519PublicKey}}";

    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("{{seed.AdminContact.Id}}"),
            Username = "{{seed.AdminContact.Username}}",
            Email = "{{seed.AdminContact.Email}}",
            X25519PublicKey = "{{seed.AdminContact.X25519PublicKey}}",
            Ed25519PublicKey = "{{seed.AdminContact.Ed25519PublicKey}}",
            IsAdmin = true,
            UpdatedAt = new System.DateTime({{seed.AdminContact.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.PUBLIC,
            SharingId = "{{seed.AdminContact.SharingId}}",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("{{seed.SystemGroup.Id}}"),
                GroupContext = "{{seed.SystemGroup.GroupContext}}",
                KeyVersion = {{seed.SystemGroup.KeyVersion}},
                GroupAdminPublicKey = "{{seed.SystemGroup.GroupAdminPublicKey}}",
                CreatedAt = new System.DateTime({{seed.SystemGroup.CreatedAt.Ticks}}L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime({{seed.SystemGroup.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "{{seed.SystemGroup.SharingId}}",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("{{seed.AdminSelfGroup.Id}}"),
                GroupContext = "{{seed.AdminSelfGroup.GroupContext}}",
                KeyVersion = {{seed.AdminSelfGroup.KeyVersion}},
                GroupAdminPublicKey = "{{seed.AdminSelfGroup.GroupAdminPublicKey}}",
                CreatedAt = new System.DateTime({{seed.AdminSelfGroup.CreatedAt.Ticks}}L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime({{seed.AdminSelfGroup.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "{{seed.AdminSelfGroup.SharingId}}",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("{{seed.AdminShareTarget.Id}}"),
                ShareGroupId = System.Guid.Parse("{{seed.AdminShareTarget.ShareGroupId}}"),
                KeyVersion = {{seed.AdminShareTarget.KeyVersion}},
                MemberPublicKey = "{{seed.AdminShareTarget.MemberPublicKey}}",
                WrappedContentKey = System.Convert.FromBase64String("{{wrappedCekBase64}}"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("{{adminSigBase64}}"),
                GroupAdminEd25519PublicKey = "{{seed.AdminShareTarget.GroupAdminEd25519PublicKey}}",
                GrantedByContactId = System.Guid.Parse("{{seed.AdminShareTarget.GrantedByContactId}}"),
                UpdatedAt = new System.DateTime({{seed.AdminShareTarget.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "{{seed.AdminShareTarget.SharingId}}",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("{{seed.AdminSelfTarget.Id}}"),
                ShareGroupId = System.Guid.Parse("{{seed.AdminSelfTarget.ShareGroupId}}"),
                KeyVersion = {{seed.AdminSelfTarget.KeyVersion}},
                MemberPublicKey = "{{seed.AdminSelfTarget.MemberPublicKey}}",
                WrappedContentKey = System.Convert.FromBase64String("{{selfWrappedCekBase64}}"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("{{selfSigBase64}}"),
                GroupAdminEd25519PublicKey = "{{seed.AdminSelfTarget.GroupAdminEd25519PublicKey}}",
                GrantedByContactId = System.Guid.Parse("{{seed.AdminSelfTarget.GrantedByContactId}}"),
                UpdatedAt = new System.DateTime({{seed.AdminSelfTarget.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "{{seed.AdminSelfTarget.SharingId}}",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("{{seed.Device.Id}}"),
            ClientGuid = "{{seed.Device.ClientGuid}}",
            DeviceName = "{{seed.Device.DeviceName}}",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("{{seed.Device.AdminContactId}}"),
            OwnContactId = System.Guid.Parse("{{seed.Device.OwnContactId}}")
        });

        modelBuilder.Entity<PermissionTableSignature>().HasData(new
        {
            Id = System.Guid.Parse("{{permSigGuid}}"),
            PermissionHash = System.Convert.FromBase64String("{{permHashBase64}}"),
            AdminSignature = System.Convert.FromBase64String("{{permSigBase64}}"),
            AdminEd25519PublicKey = "{{adminKeys.Ed25519PublicKey}}"
        });
    }
}
""";

var fullPath = Path.GetFullPath(outputPath);
var dir = Path.GetDirectoryName(fullPath);
if (dir is not null && !Directory.Exists(dir))
{
    Directory.CreateDirectory(dir);
}
await File.WriteAllTextAsync(fullPath, code);
Console.WriteLine($"Admin seed written to: {fullPath}");
Console.WriteLine($"Context: {ns}.{contextName}");
Console.WriteLine($"Admin contact: {seed.AdminContact.Username} ({seed.AdminContact.Email})");
Console.WriteLine($"System group: {seed.SystemGroup.GroupContext}");
Console.WriteLine($"Permission table: {allPermissions.Length} rows, hash={permHashBase64[..16]}…");

/// <summary>
/// Resolve all permissions: system (hardcoded) + domain (generator-emitted).
/// Loads the target context's assembly and calls GetDomainPermissions() if available.
/// </summary>
static SyncPermission[] ResolveAllPermissions(string ns, string contextName)
{
    var system = CryptoSyncContextBase.GetSystemPermissions();

    // Try to find the generated GetDomainPermissions on the target context.
    var fullTypeName = $"{ns}.{contextName}";

    // Load all referenced assemblies — .NET doesn't auto-load transitives.
    foreach (var asmPath in Directory.GetFiles(AppContext.BaseDirectory, "*.dll"))
    {
        try
        {
            System.Reflection.Assembly.LoadFrom(asmPath);
        }
        catch
        {
            // Skip assemblies that can't be loaded
        }
    }

    var contextType = AppDomain.CurrentDomain.GetAssemblies()
        .Select(a => a.GetType(fullTypeName))
        .FirstOrDefault(t => t is not null);

    if (contextType is null)
    {
        Console.WriteLine($"  (context '{fullTypeName}' not found — system permissions only)");
        return system;
    }

    var method = contextType.GetMethod("GetDomainPermissions",
        System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);

    if (method is null)
    {
        Console.WriteLine($"  (no GetDomainPermissions on '{contextName}' — system permissions only)");
        return system;
    }

    var domain = (SyncPermission[])method.Invoke(null, null)!;
    Console.WriteLine($"  Found {domain.Length} domain permission(s) from {contextName}");
    return system.Concat(domain).ToArray();
}
