using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using SqliteWasmBlazor.CryptoSync.Generator;
using SqliteWasmBlazor.CryptoSync.Generator.Tests.Helpers;

namespace SqliteWasmBlazor.CryptoSync.Generator.Tests;

internal class CryptoSyncGeneratorTest : CSharpSourceGeneratorTest<CryptoSyncGenerator, DefaultVerifier>
{
    public CryptoSyncGeneratorTest()
    {
        ReferenceAssemblies = TestShared.ReferenceAssemblies();
    }

    protected override ParseOptions CreateParseOptions()
    {
        return new CSharpParseOptions(languageVersion: LanguageVersion.Preview);
    }
}

public class CryptoSyncGeneratorTests
{
    private static readonly string StubTypes = """
        namespace System.ComponentModel.DataAnnotations
        {
            [System.AttributeUsage(System.AttributeTargets.Property)]
            public class MaxLengthAttribute : System.Attribute
            {
                public MaxLengthAttribute(int length) { }
            }
        }
        namespace Microsoft.EntityFrameworkCore
        {
            public class DbContext
            {
                protected virtual void OnModelCreating(ModelBuilder modelBuilder) { }
                public DbSet<T> Set<T>() where T : class => new();
            }
            public class DbSet<T> where T : class { }
            public class ModelBuilder
            {
                public EntityTypeBuilder<T> Entity<T>(System.Action<EntityTypeBuilder<T>> config) where T : class { config(new()); return new(); }
            }
            public class EntityTypeBuilder<T> where T : class
            {
                public EntityTypeBuilder<T> ToTable(string name) => this;
                public EntityTypeBuilder<T> HasKey(System.Linq.Expressions.Expression<System.Func<T, object>> expr) => this;
                public EntityTypeBuilder<T> HasIndex(System.Linq.Expressions.Expression<System.Func<T, object>> expr) => this;
            }
            public class DbContextOptions { }
            public class DbContextOptions<T> : DbContextOptions where T : DbContext { }
        }
        namespace SqliteWasmBlazor.CryptoSync
        {
            public enum SharingScope { Public = 0, Shared = 1, Client = 2 }
            public abstract class SyncableEntity
            {
                public System.Guid Id { get; set; }
                public SharingScope SharingScope { get; set; }
                public string SharingId { get; set; } = "";
                public System.DateTime UpdatedAt { get; set; }
                public bool IsDeleted { get; set; }
                public System.DateTime? DeletedAt { get; set; }
            }
            public abstract class CryptoSyncContextBase : Microsoft.EntityFrameworkCore.DbContext
            {
                protected CryptoSyncContextBase(Microsoft.EntityFrameworkCore.DbContextOptions options) : base() { }
            }
        }
        """;

    // ============================================================
    // EXACT SOURCE MATCH: crypto entity + config + registry
    // ============================================================

    [Fact]
    public async Task SingleEntity_ExactSourceMatch()
    {
        var source = StubTypes + """
            namespace TestApp
            {
                public class TodoItem : SqliteWasmBlazor.CryptoSync.SyncableEntity
                {
                    public string Title { get; set; } = "";
                    public bool IsCompleted { get; set; }
                }

                public partial class MyContext : SqliteWasmBlazor.CryptoSync.CryptoSyncContextBase
                {
                    public MyContext(Microsoft.EntityFrameworkCore.DbContextOptions options) : base(options) { }
                    public Microsoft.EntityFrameworkCore.DbSet<TodoItem> TodoItems => Set<TodoItem>();
                }
            }
            """;

        var expectedEntity = NormalizeLineEndings("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.ComponentModel.DataAnnotations;

            namespace TestApp;

            /// <summary>
            /// Shadow crypto table for TodoItem. Contains encrypted row data.
            /// Generated by CryptoSyncGenerator — do not edit.
            /// </summary>
            public sealed class Crypto_TodoItem
            {
                public Guid Id { get; set; }

                /// <summary>0=Public, 1=Shared, 2=Client</summary>
                public int SharingScope { get; set; }

                [MaxLength(128)]
                public required string SharingId { get; init; }

                /// <summary>AES-GCM encrypted row data (ALL columns).</summary>
                public required byte[] EncryptedRow { get; init; }

                /// <summary>Per-row AES-GCM nonce.</summary>
                public required byte[] Nonce { get; init; }
            }

            """);

        var expectedConfig = NormalizeLineEndings("""
            // <auto-generated/>
            #nullable enable

            using Microsoft.EntityFrameworkCore;

            namespace TestApp;

            public partial class MyContext
            {
                /// <summary>
                /// Configure crypto shadow tables. Call from OnModelCreating.
                /// Generated by CryptoSyncGenerator.
                /// </summary>
                protected void ConfigureCryptoTables(ModelBuilder modelBuilder)
                {
                    modelBuilder.Entity<Crypto_TodoItem>(e =>
                    {
                        e.ToTable("_crypto_TodoItems");
                        e.HasKey(x => x.Id);
                        e.HasIndex(x => x.SharingId);
                        e.HasIndex(x => x.SharingScope);
                    });

                }
            }

            """);

        var expectedRegistry = NormalizeLineEndings("""
            // <auto-generated/>
            #nullable enable

            namespace TestApp;

            /// <summary>
            /// Registry of all crypto shadow tables. Generated by CryptoSyncGenerator.
            /// </summary>
            public static class CryptoTableRegistry
            {
                public static readonly (string EntityName, string CryptoTableName, string OpenTableName)[] Tables =
                [
                    ("TodoItem", "_crypto_TodoItems", "TodoItems"),
                ];
            }

            """);

        var test = new CryptoSyncGeneratorTest { TestCode = source };
        test.TestState.GeneratedSources.Add(
            (typeof(CryptoSyncGenerator), "Crypto_TodoItem.g.cs",
                SourceText.From(expectedEntity, Encoding.UTF8)));
        test.TestState.GeneratedSources.Add(
            (typeof(CryptoSyncGenerator), "MyContext_CryptoConfig.g.cs",
                SourceText.From(expectedConfig, Encoding.UTF8)));
        test.TestState.GeneratedSources.Add(
            (typeof(CryptoSyncGenerator), "CryptoTableRegistry.g.cs",
                SourceText.From(expectedRegistry, Encoding.UTF8)));

        await test.RunAsync();
    }

    // ============================================================
    // MULTIPLE ENTITIES
    // ============================================================

    [Fact]
    public async Task MultipleEntities_GeneratesAll()
    {
        var source = StubTypes + """
            namespace TestApp
            {
                public class Item1 : SqliteWasmBlazor.CryptoSync.SyncableEntity { }
                public class Item2 : SqliteWasmBlazor.CryptoSync.SyncableEntity { }

                public partial class MultiContext : SqliteWasmBlazor.CryptoSync.CryptoSyncContextBase
                {
                    public MultiContext(Microsoft.EntityFrameworkCore.DbContextOptions options) : base(options) { }
                    public Microsoft.EntityFrameworkCore.DbSet<Item1> Items1 => Set<Item1>();
                    public Microsoft.EntityFrameworkCore.DbSet<Item2> Items2 => Set<Item2>();
                }
            }
            """;

        var test = new CryptoSyncGeneratorTest
        {
            TestCode = source,
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };
        await test.RunAsync();
    }

    // ============================================================
    // SYSTEM TABLE EXCLUSION
    // ============================================================

    [Fact]
    public async Task SkipsSystemTables()
    {
        var source = StubTypes + """
            namespace TestApp
            {
                public class MyEntity : SqliteWasmBlazor.CryptoSync.SyncableEntity { }

                public partial class TestCtx : SqliteWasmBlazor.CryptoSync.CryptoSyncContextBase
                {
                    public TestCtx(Microsoft.EntityFrameworkCore.DbContextOptions options) : base(options) { }
                    public Microsoft.EntityFrameworkCore.DbSet<MyEntity> MyEntities => Set<MyEntity>();
                }
            }
            """;

        var test = new CryptoSyncGeneratorTest
        {
            TestCode = source,
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };
        await test.RunAsync();
    }

    // ============================================================
    // NO CONTEXT = NO GENERATION
    // ============================================================

    [Fact]
    public async Task NoContext_NoGeneration()
    {
        var source = StubTypes + """
            namespace TestApp
            {
                public class SomeEntity : SqliteWasmBlazor.CryptoSync.SyncableEntity { }
            }
            """;

        var test = new CryptoSyncGeneratorTest
        {
            TestCode = source,
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };
        await test.RunAsync();
    }

    // ============================================================
    // ABSTRACT CONTEXT SKIPPED
    // ============================================================

    [Fact]
    public async Task AbstractContext_Skipped()
    {
        var source = StubTypes + """
            namespace TestApp
            {
                public class MyEntity : SqliteWasmBlazor.CryptoSync.SyncableEntity { }

                public abstract partial class AbstractCtx : SqliteWasmBlazor.CryptoSync.CryptoSyncContextBase
                {
                    protected AbstractCtx(Microsoft.EntityFrameworkCore.DbContextOptions options) : base(options) { }
                    public Microsoft.EntityFrameworkCore.DbSet<MyEntity> MyEntities => Set<MyEntity>();
                }
            }
            """;

        var test = new CryptoSyncGeneratorTest
        {
            TestCode = source,
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck
        };
        await test.RunAsync();
    }

    private static string NormalizeLineEndings(string text)
    {
        return text.Replace("\r\n", "\n").Replace("\n", Environment.NewLine);
    }
}
