// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output ../SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.CryptoSync.Tests;

public partial class TestSyncContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    /// <summary>
    /// Seeds the admin bootstrap data: <c>TrustedContact</c>, the system
    /// <c>ShareGroup</c> + admin's <c>ShareTarget</c>, the admin's private
    /// self-<c>ShareGroup</c> + self-<c>ShareTarget</c> (for client-scoped
    /// records), and <c>DeviceSettings</c>.
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("d50f504f-520c-44b0-bb2a-46d21387ae98"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("7a4ff32a-04cd-40f2-96f5-fc929680e376"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("635f2a53-0d20-4c56-804a-907f424c46cb"),
                GroupContext = "self-d50f504f520c44b0bb2a46d21387ae98:v1",
                KeyVersion = 1,
                AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("6c4e8c0e-f5c7-4c2f-b6c5-03fb4306f058"),
                ShareGroupId = System.Guid.Parse("7a4ff32a-04cd-40f2-96f5-fc929680e376"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("T6KheBqOHL8uJ9B7idhUeC3rLMoyXGzno0LTtTTAnOuIVJnMhqWmiMEFUG4z89pNhMTWyxoMs8kFeNA3"),
                Role = SyncRole.Owner,
                GrantedByContactId = System.Guid.Parse("d50f504f-520c-44b0-bb2a-46d21387ae98"),
                UpdatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("d0d1d0dd-f19e-41e3-bd1f-490b0cec2a9b"),
                ShareGroupId = System.Guid.Parse("635f2a53-0d20-4c56-804a-907f424c46cb"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("XGuyaZvFcEKm0lAfPDkB5naXX+B4FkOxelLFispCBANyzCXbud3Lh3KE2VEY+BfGb+8rMqiUSJlpK9Ne"),
                Role = SyncRole.Owner,
                GrantedByContactId = System.Guid.Parse("d50f504f-520c-44b0-bb2a-46d21387ae98"),
                UpdatedAt = new System.DateTime(639115398063975130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("e1d0e6e6-bb32-4039-9ef0-8ae97d7e9112"),
            ClientGuid = "ef4b21e7-4640-4746-879c-e5532fb0b06e",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("d50f504f-520c-44b0-bb2a-46d21387ae98"),
            OwnContactId = System.Guid.Parse("d50f504f-520c-44b0-bb2a-46d21387ae98")
        });
    }
}