// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output ../SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.CryptoSync.Tests;

public partial class TestSyncContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    /// <summary>
    /// Seeds the admin bootstrap data: <c>TrustedContact</c>, the system
    /// <c>ShareGroup</c> + admin's <c>ShareTarget</c>, the admin's private
    /// self-<c>ShareGroup</c> + self-<c>ShareTarget</c> (for client-scoped
    /// records), and <c>DeviceSettings</c>.
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("965df86d-4d39-4fef-9f47-9b8a29b6bd95"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("85d2d8b8-ffaf-40a3-846b-a0e6bbb10934"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("5cb8dce0-a4e7-4a94-9e1b-2ce153629f4c"),
                GroupContext = "self-965df86d4d394fef9f479b8a29b6bd95:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("33943ebb-9924-4940-b2b6-bf884f498d9c"),
                ShareGroupId = System.Guid.Parse("85d2d8b8-ffaf-40a3-846b-a0e6bbb10934"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("gQHONhYugkiEXIQer/i/pU2fWPwfQ+cOb23VnHqfKaYHES7R9xF/+UWvKWclSY9/lUSa78gF/LTIpndx"),
                Role = SyncRole.Owner,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("965df86d-4d39-4fef-9f47-9b8a29b6bd95"),
                UpdatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("8b4ba125-da2f-4a20-a490-b425ce724021"),
                ShareGroupId = System.Guid.Parse("5cb8dce0-a4e7-4a94-9e1b-2ce153629f4c"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("KtXdjdSOEE9a/Qq+3CXw5OC7edgXrLSWFKx5PEktpC2jEn+1Q9gJ6r6oOgmbBuTPIUdT20wTexuaKA6r"),
                Role = SyncRole.Owner,
                AdminSignature = System.Convert.FromBase64String("Zz/J7Sx4TXKEkUbpy2XV77tJcMOcrhHBJtnv43cDCHTZVb/45vh4lt+kItjz5Os0mzJf3krnNP9/v/AyRouNBA=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("965df86d-4d39-4fef-9f47-9b8a29b6bd95"),
                UpdatedAt = new System.DateTime(639116115066396130L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("e9645015-cf09-428b-83e3-f4eb9c052a4b"),
            ClientGuid = "ebb48cab-a71c-4609-a569-2995b636dbfc",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("965df86d-4d39-4fef-9f47-9b8a29b6bd95"),
            OwnContactId = System.Guid.Parse("965df86d-4d39-4fef-9f47-9b8a29b6bd95")
        });
    }
}