using BlazorPRF.Crypto.Abstractions.Services;
using BlazorPRF.Crypto.Testing;
using SqliteWasmBlazor.CryptoSync;

// ============================================================================
// Admin Seed Generator
//
// Runs CryptoSyncBootstrap with a hardcoded test keypair and emits a .cs file
// with HasData calls that the consumer's DbContext includes in OnModelCreating.
//
// Usage: dotnet run -- --context TestSyncContext --namespace SqliteWasmBlazor.CryptoSync.Tests --output ../SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs
// ============================================================================

var contextName = "TestSyncContext";
var ns = "SqliteWasmBlazor.CryptoSync.Tests";
var outputPath = "../SqliteWasmBlazor.CryptoSync.Tests/AdminSeed.g.cs";

// Parse args
for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--context" when i + 1 < args.Length:
            contextName = args[++i];
            break;
        case "--namespace" when i + 1 < args.Length:
            ns = args[++i];
            break;
        case "--output" when i + 1 < args.Length:
            outputPath = args[++i];
            break;
    }
}

// Hardcoded test seed — deterministic so the generated file is stable across runs.
// In production, the admin's PRF-derived keypair would be used instead.
var crypto = new BouncyCastleCryptoProvider();
var groupEncryption = new GroupEncryptionService(crypto);
var declarationSigner = new DeclarationSigner(crypto);
var bootstrap = new CryptoSyncBootstrap(groupEncryption, declarationSigner);

var adminSeed = new byte[32];
for (var i = 0; i < 32; i++)
{
    adminSeed[i] = (byte)(i + 1);
}
var adminKeys = await crypto.DeriveDualKeyPairAsync(adminSeed);

var seed = await bootstrap.CreateAdminSeedAsync(
    adminKeys,
    adminUsername: "TestAdmin",
    adminEmail: "admin@test.local",
    deviceName: "Seed Device");

// Emit .cs file
var wrappedCekBase64 = Convert.ToBase64String(seed.AdminShareTarget.WrappedContentKey);
var selfWrappedCekBase64 = Convert.ToBase64String(seed.AdminSelfTarget.WrappedContentKey);
var adminSigBase64 = Convert.ToBase64String(seed.AdminShareTarget.AdminSignature);
var selfSigBase64 = Convert.ToBase64String(seed.AdminSelfTarget.AdminSignature);

var code = $$"""
// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context {{contextName}} --namespace {{ns}} --output {{outputPath}}
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace {{ns}};

public partial class {{contextName}}
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "{{adminKeys.X25519PrivateKey}}";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "{{adminKeys.Ed25519PrivateKey}}";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "{{adminKeys.X25519PublicKey}}";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "{{adminKeys.Ed25519PublicKey}}";

    /// <summary>
    /// Seeds the admin bootstrap data: <c>TrustedContact</c>, the system
    /// <c>ShareGroup</c> + admin's <c>ShareTarget</c>, the admin's private
    /// self-<c>ShareGroup</c> + self-<c>ShareTarget</c> (for client-scoped
    /// records), and <c>DeviceSettings</c>.
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("{{seed.AdminContact.Id}}"),
            Username = "{{seed.AdminContact.Username}}",
            Email = "{{seed.AdminContact.Email}}",
            X25519PublicKey = "{{seed.AdminContact.X25519PublicKey}}",
            Ed25519PublicKey = "{{seed.AdminContact.Ed25519PublicKey}}",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime({{seed.AdminContact.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "{{seed.AdminContact.SharingId}}",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("{{seed.SystemGroup.Id}}"),
                GroupContext = "{{seed.SystemGroup.GroupContext}}",
                KeyVersion = {{seed.SystemGroup.KeyVersion}},
                GroupAdminPublicKey = "{{seed.SystemGroup.GroupAdminPublicKey}}",
                CreatedAt = new System.DateTime({{seed.SystemGroup.CreatedAt.Ticks}}L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime({{seed.SystemGroup.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "{{seed.SystemGroup.SharingId}}",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("{{seed.AdminSelfGroup.Id}}"),
                GroupContext = "{{seed.AdminSelfGroup.GroupContext}}",
                KeyVersion = {{seed.AdminSelfGroup.KeyVersion}},
                GroupAdminPublicKey = "{{seed.AdminSelfGroup.GroupAdminPublicKey}}",
                CreatedAt = new System.DateTime({{seed.AdminSelfGroup.CreatedAt.Ticks}}L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime({{seed.AdminSelfGroup.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "{{seed.AdminSelfGroup.SharingId}}",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("{{seed.AdminShareTarget.Id}}"),
                ShareGroupId = System.Guid.Parse("{{seed.AdminShareTarget.ShareGroupId}}"),
                KeyVersion = {{seed.AdminShareTarget.KeyVersion}},
                MemberPublicKey = "{{seed.AdminShareTarget.MemberPublicKey}}",
                WrappedContentKey = System.Convert.FromBase64String("{{wrappedCekBase64}}"),
                Role = SyncRole.Owner,
                AdminSignature = System.Convert.FromBase64String("{{adminSigBase64}}"),
                GroupAdminEd25519PublicKey = "{{seed.AdminShareTarget.GroupAdminEd25519PublicKey}}",
                GrantedByContactId = System.Guid.Parse("{{seed.AdminShareTarget.GrantedByContactId}}"),
                UpdatedAt = new System.DateTime({{seed.AdminShareTarget.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "{{seed.AdminShareTarget.SharingId}}",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("{{seed.AdminSelfTarget.Id}}"),
                ShareGroupId = System.Guid.Parse("{{seed.AdminSelfTarget.ShareGroupId}}"),
                KeyVersion = {{seed.AdminSelfTarget.KeyVersion}},
                MemberPublicKey = "{{seed.AdminSelfTarget.MemberPublicKey}}",
                WrappedContentKey = System.Convert.FromBase64String("{{selfWrappedCekBase64}}"),
                Role = SyncRole.Owner,
                AdminSignature = System.Convert.FromBase64String("{{selfSigBase64}}"),
                GroupAdminEd25519PublicKey = "{{seed.AdminSelfTarget.GroupAdminEd25519PublicKey}}",
                GrantedByContactId = System.Guid.Parse("{{seed.AdminSelfTarget.GrantedByContactId}}"),
                UpdatedAt = new System.DateTime({{seed.AdminSelfTarget.UpdatedAt.Ticks}}L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "{{seed.AdminSelfTarget.SharingId}}",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("{{seed.Device.Id}}"),
            ClientGuid = "{{seed.Device.ClientGuid}}",
            DeviceName = "{{seed.Device.DeviceName}}",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("{{seed.Device.AdminContactId}}"),
            OwnContactId = System.Guid.Parse("{{seed.Device.OwnContactId}}")
        });
    }
}
""";

var fullPath = Path.GetFullPath(outputPath);
var dir = Path.GetDirectoryName(fullPath);
if (dir is not null && !Directory.Exists(dir))
{
    Directory.CreateDirectory(dir);
}
await File.WriteAllTextAsync(fullPath, code);
Console.WriteLine($"Admin seed written to: {fullPath}");
Console.WriteLine($"Context: {ns}.{contextName}");
Console.WriteLine($"Admin contact: {seed.AdminContact.Username} ({seed.AdminContact.Email})");
Console.WriteLine($"System group: {seed.SystemGroup.GroupContext}");
