// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output ../SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    /// <summary>
    /// Seeds the admin bootstrap data: <c>TrustedContact</c>, the system
    /// <c>ShareGroup</c> + admin's <c>ShareTarget</c>, the admin's private
    /// self-<c>ShareGroup</c> + self-<c>ShareTarget</c> (for client-scoped
    /// records), and <c>DeviceSettings</c>.
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("218b07af-4923-4f23-afca-d4077ca8b95d"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("1b0b5d43-e5a3-49a1-8b1b-92602532c5c4"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("1a2707fc-4c1a-4a14-9572-c0e042924903"),
                GroupContext = "self-218b07af49234f23afcad4077ca8b95d:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("56291c01-e16e-41d2-b978-9332403c3023"),
                ShareGroupId = System.Guid.Parse("1b0b5d43-e5a3-49a1-8b1b-92602532c5c4"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("5kBIsSpP5PZ1UolHWpwgYJJa0hFY+smTaYxI7Bkx6y2RoRy4FxmXchtJ4YR4nd0UAagrm/uu4ncpmInn"),
                Role = SyncRole.Owner,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("218b07af-4923-4f23-afca-d4077ca8b95d"),
                UpdatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("ee4d51c0-01c5-430d-a789-7f9eda578bac"),
                ShareGroupId = System.Guid.Parse("1a2707fc-4c1a-4a14-9572-c0e042924903"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("OTPzzBYnW3A0Ozvuz5ZGGk+rTrinzoErAKkxL6RJ9vbT7vuGcbUUMieOmpLdul5ny7vH19o2+sj+OoeV"),
                Role = SyncRole.Owner,
                AdminSignature = System.Convert.FromBase64String("s1YNaqGpZ5Bx3Mwckx6I64SmNJ17qhzWaDr6wZaCLHQVhOdbxWDT0hyBsSnVuLeMZT6CJMZRva4pdFgrPbAXCw=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("218b07af-4923-4f23-afca-d4077ca8b95d"),
                UpdatedAt = new System.DateTime(639116115084816750L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("52a20023-87de-429d-9bd8-765ae04c7875"),
            ClientGuid = "e6fd3c78-dc09-4588-923a-e57c92dd9a9a",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("218b07af-4923-4f23-afca-d4077ca8b95d"),
            OwnContactId = System.Guid.Parse("218b07af-4923-4f23-afca-d4077ca8b95d")
        });
    }
}