// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("49d36bd2-df24-4258-82bc-aa87f6a5401a"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            UpdatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.PUBLIC,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("67adccd3-c41d-4c31-8171-82848b5c4378"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("d2c34a98-05aa-412f-9870-1b6d25bf9752"),
                GroupContext = "self-49d36bd2df24425882bcaa87f6a5401a:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("d3e9b01f-cdfc-47ad-86da-5b94673a3261"),
                ShareGroupId = System.Guid.Parse("67adccd3-c41d-4c31-8171-82848b5c4378"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("wm4MHWKuifVUw/QCF08xeOH9l9HmVJorC9Z/cZ1NyxqZKNGdXwqiO7DtktBLxRVkIufGLzWgUoPcf2lX"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("49d36bd2-df24-4258-82bc-aa87f6a5401a"),
                UpdatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("4f22ea38-b91e-42a3-90f9-550cbda48036"),
                ShareGroupId = System.Guid.Parse("d2c34a98-05aa-412f-9870-1b6d25bf9752"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("gqyzB1XtJSLrC+nAEwpqwI4PYx1BKFws+kwbJQ7m9UXLE/Wn2JqwI2U/rGLt/TtREoidSnrWJc1E0rD7"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("kMfWHn009cN46zkp1g5XGKvTyVJJhFOUhnA64OuMJYpfsrkIQ+80gx2XDDGZaLDCfIpB9z+kY+QsTEFc/8H/CQ=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("49d36bd2-df24-4258-82bc-aa87f6a5401a"),
                UpdatedAt = new System.DateTime(639116691504857250L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("1a32e095-13ea-4dd8-8956-c6c8081974f3"),
            ClientGuid = "d537409f-7527-49ba-b4b2-721f67719620",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("49d36bd2-df24-4258-82bc-aa87f6a5401a"),
            OwnContactId = System.Guid.Parse("49d36bd2-df24-4258-82bc-aa87f6a5401a")
        });

        modelBuilder.Entity<PermissionTableSignature>().HasData(new
        {
            Id = System.Guid.Parse("ece64655-8999-3ed3-a68d-25b617087d86"),
            PermissionHash = System.Convert.FromBase64String("NiLUetu9cIOTwWkxyjgsVhpK7/TgqNQjV0KKiy1wjmw="),
            AdminSignature = System.Convert.FromBase64String("KNKFzOw9/9UHse0cFMWJh1+uZoqzNYUAXG8Q8WbD7BPhyj+dRIxBTs07wseo0tetCFEpZu8R2k+kbpwa33XFAA=="),
            AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA="
        });
    }
}