// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output ../SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    /// <summary>
    /// Seeds the admin bootstrap data: <c>TrustedContact</c>, the system
    /// <c>ShareGroup</c> + admin's <c>ShareTarget</c>, the admin's private
    /// self-<c>ShareGroup</c> + self-<c>ShareTarget</c> (for client-scoped
    /// records), and <c>DeviceSettings</c>.
    /// Call from <see cref="OnModelCreating"/> after <c>base.OnModelCreating</c> and <c>ConfigureCryptoTables</c>.
    /// </summary>
    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("868494ad-a945-4466-8f90-ef5b41508bd0"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            IsTrusted = true,
            UpdatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.Public,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("7bb5c078-718a-47e0-a497-9bc6e3ad56a9"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("9853b162-e371-43d9-bfff-244806fb3e44"),
                GroupContext = "self-868494ada94544668f90ef5b41508bd0:v1",
                KeyVersion = 1,
                AdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("0847a67c-3669-49c0-a697-1266a783ea86"),
                ShareGroupId = System.Guid.Parse("7bb5c078-718a-47e0-a497-9bc6e3ad56a9"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("m3C2V+5WXucMoj0WuwP2Blv7EkNyDl10S8YFAOi+ulaF0ywQvUJp5xZMGOcr6xzg/RbAQyqv587z1Upy"),
                Role = SyncRole.Owner,
                GrantedByContactId = System.Guid.Parse("868494ad-a945-4466-8f90-ef5b41508bd0"),
                UpdatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Public,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("9f4e4d02-461e-473b-a160-40e1a4e4c592"),
                ShareGroupId = System.Guid.Parse("9853b162-e371-43d9-bfff-244806fb3e44"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("mFNJ8wLOTHxlERxJkc/Wa/RnzDTHoqwbCn0knQBxyIo8lMcE4Mrp83kRehdQTmZs4idOF7GkLsKcvv45"),
                Role = SyncRole.Owner,
                GrantedByContactId = System.Guid.Parse("868494ad-a945-4466-8f90-ef5b41508bd0"),
                UpdatedAt = new System.DateTime(639115398305701200L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.Client,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("4125451a-be37-4658-9472-fbb317034c6e"),
            ClientGuid = "da14cd6c-d2d6-46e7-a0f6-7e1f9738e10b",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("868494ad-a945-4466-8f90-ef5b41508bd0"),
            OwnContactId = System.Guid.Parse("868494ad-a945-4466-8f90-ef5b41508bd0")
        });
    }
}