// <auto-generated>
// Generated by SqliteWasmBlazor.AdminSeed — do not edit manually.
// Re-run: dotnet run --project SqliteWasmBlazor.AdminSeed -- --context CryptoTestContext --namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync --output ../SqliteWasmBlazor.TestApp/TestInfrastructure/CryptoSync/AdminSeed.g.cs
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore;
using SqliteWasmBlazor.CryptoSync;

namespace SqliteWasmBlazor.TestApp.TestInfrastructure.CryptoSync;

public partial class CryptoTestContext
{
    /// <summary>Admin X25519 private key (Base64) — for test key derivation. DO NOT use in production.</summary>
    public const string AdminX25519PrivateKey = "6CDgPqpdtg76hTQwx+NvW10UkPMrs8gSv0qIJUWc/Js=";

    /// <summary>Admin Ed25519 private key (Base64) — for test signing. DO NOT use in production.</summary>
    public const string AdminEd25519PrivateKey = "0AMxvmHQ2YmRRNe9TblNSeqX1Eo/O2jNu6bvMOu8SAQ=";

    /// <summary>Admin X25519 public key (Base64).</summary>
    public const string AdminX25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=";

    /// <summary>Admin Ed25519 public key (Base64).</summary>
    public const string AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=";

    protected void SeedAdminBootstrap(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TrustedContact>().HasData(new
        {
            Id = System.Guid.Parse("927ecbfd-b555-4d7b-af5e-70bbc2884e9d"),
            Username = "TestAdmin",
            Email = "admin@test.local",
            X25519PublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
            Ed25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
            IsAdmin = true,
            UpdatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
            SharingScope = SharingScope.PUBLIC,
            SharingId = "system",
            IsDeleted = false
        });

        modelBuilder.Entity<ShareGroup>().HasData(
            new
            {
                Id = System.Guid.Parse("6ffbb3cf-a26e-412e-8189-76bcfbbad60a"),
                GroupContext = "system:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("2cd2d726-1b01-47f0-a6b2-37da8a2b2332"),
                GroupContext = "self-927ecbfdb5554d7baf5e70bbc2884e9d:v1",
                KeyVersion = 1,
                GroupAdminPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                CreatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
                UpdatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<ShareTarget>().HasData(
            new
            {
                Id = System.Guid.Parse("b58a401e-80bb-40fc-8bf0-183bd34aff68"),
                ShareGroupId = System.Guid.Parse("6ffbb3cf-a26e-412e-8189-76bcfbbad60a"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("qVTcowJUCLzclHCr2RzIN91dfS9NC70SmkvJ9ZHKPcgAc/ZWi4cQJ3cee34oppj+jVDefVPvD/NP78Xf"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("ryoLwPSgB3y/47bNfJ3NlCAdxee9AohC51Bz8by52yKhZdVs8ORXhiK+plBd7jyhZjKfmkoapDr4Y+GcdHlYBg=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("927ecbfd-b555-4d7b-af5e-70bbc2884e9d"),
                UpdatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.PUBLIC,
                SharingId = "system",
                IsDeleted = false
            },
            new
            {
                Id = System.Guid.Parse("b6c4b808-b7d6-48b6-96f2-67c11b05106f"),
                ShareGroupId = System.Guid.Parse("2cd2d726-1b01-47f0-a6b2-37da8a2b2332"),
                KeyVersion = 1,
                MemberPublicKey = "hsX5Q3fWqD8zyCsMe5PksvoDKUCckQUgYK90hdfxHm4=",
                WrappedContentKey = System.Convert.FromBase64String("kJ5bvo4hc6DuIhEMXAGdoyf7svdcWgYy6wHfYgZgfdcQPWZVjBDB7tWvVLiNyIqUu7jPcPBP5kHR9VgJ"),
                Role = SyncRole.OWNER,
                AdminSignature = System.Convert.FromBase64String("+Nz+HpSSasQIC0A1WKapQVQ806Up9ypPUl9BuFIP55TNWAkPHyrM5xkww9t4QH7MoWxuCZufJcoyBClebuyLDA=="),
                GroupAdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA=",
                GrantedByContactId = System.Guid.Parse("927ecbfd-b555-4d7b-af5e-70bbc2884e9d"),
                UpdatedAt = new System.DateTime(639131736976077490L, System.DateTimeKind.Utc),
                SharingScope = SharingScope.CLIENT,
                SharingId = "system",
                IsDeleted = false
            });

        modelBuilder.Entity<DeviceSettings>().HasData(new
        {
            Id = System.Guid.Parse("7d6deee2-3540-4cf5-9510-59a491e1bb42"),
            ClientGuid = "123c2fa6-f535-4f0c-a110-bd2aba0d53f0",
            DeviceName = "Seed Device",
            IsAdmin = true,
            AdminContactId = System.Guid.Parse("927ecbfd-b555-4d7b-af5e-70bbc2884e9d"),
            OwnContactId = System.Guid.Parse("927ecbfd-b555-4d7b-af5e-70bbc2884e9d")
        });

        modelBuilder.Entity<PermissionTableSignature>().HasData(new
        {
            Id = System.Guid.Parse("ece64655-8999-3ed3-a68d-25b617087d86"),
            PermissionHash = System.Convert.FromBase64String("+ECaUtErN+Oer2R+WXqF8T/m/XycewqFjt0X6r1F5Nk="),
            AdminSignature = System.Convert.FromBase64String("r44FQMFe6KRG3ow662O0mmgJejCxrXIPqu63S3ZYTy1MIQicNrrXGj1UUJPXg9QgSqZmep01KL9SWkD7BLX/Dg=="),
            AdminEd25519PublicKey = "OBZwE49/GjJM9BteHA/VohAr2v3ScBHgknhQ4F4lJFA="
        });
    }
}